-- Snapifit AI Production Database Schema
-- Exported from Supabase production environment on 2025-06-10
-- Project: vdjnnaunrtjhfnpuarrw
--
-- This file contains the complete production database structure including:
-- - 18 functions (all business logic)
-- - 4 triggers (automatic timestamp updates)
-- - 6 tables (complete data structure)
-- - All indexes and constraints
--
-- Statistics:
-- - Functions: 18 个
-- - Triggers: 4 个
-- - Tables: 6 个
-- - Schema file size: 50KB
--
-- Key Functions Included:
-- ✅ atomic_usage_check_and_increment - Usage control
-- ✅ upsert_log_patch - Log updates with optimistic locking
-- ✅ jsonb_deep_merge - JSON deep merge utility
-- ✅ get_user_profile - User profile retrieval
--
-- Usage:
-- psql -d your_database -f database/schema_production.sql
--
-- Note: This file should be copied from the Ubuntu export:
-- ~/snapfit-export/database_backup/schema.sql
--
-- To update this file:
-- 1. Export from production: supabase db dump --linked -f schema.sql
-- 2. Copy the exported file to replace this one
-- 3. Update the header comments with new statistics

-- TODO: Copy the actual schema content from Ubuntu export
-- The actual schema content should be copied from:
-- ~/snapfit-export/database_backup/schema.sql

-- Placeholder - replace with actual production schema
SELECT 'This file needs to be updated with the actual production schema from Ubuntu export' as notice;
